# Generated by Django 3.1.4 on 2020-12-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paper_size',
            field=models.CharField(choices=[('a4', 'a4'), ('a5', 'a5'), ('b5', 'b5')], default='a4', max_length=300),
        ),
    ]
