# Generated by Django 3.1.4 on 2020-12-08 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userside', '0002_order_paper_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_acc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_size',
            field=models.CharField(choices=[('a4', 'a4'), ('a5', 'a5'), ('b5', 'b5'), ('b4', 'b4')], default='a4', max_length=300),
        ),
    ]
