# Generated by Django 3.1.4 on 2020-12-08 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_auto_20201208_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bending_type',
            field=models.CharField(choices=[('booklet', 'booklet'), ('book', 'book'), ('clips', 'clips')], default='clips', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='data_orderd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='order_statis',
            field=models.CharField(choices=[('pending', 'pending'), ('working on', 'working on'), ('deliverd', 'deliverd'), ('complete', 'complete')], default='pending', max_length=300),
        ),
    ]
