# Generated by Django 3.1.4 on 2020-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_auto_20201208_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
