# Generated by Django 3.1.4 on 2020-12-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_auto_20201208_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_acc',
            new_name='user_acount',
        ),
        migrations.AlterField(
            model_name='order',
            name='bending_type',
            field=models.CharField(choices=[('booklet', 'booklet'), ('book', 'book'), ('side clips', 'side clips'), ('corner clips', 'corner clips')], default='clips', max_length=300),
        ),
    ]
