# Generated by Django 3.1.4 on 2020-12-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_auto_20201214_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
