# Generated by Django 3.1.4 on 2020-12-18 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userside', '0007_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('paper_size', models.CharField(choices=[('a4', 'a4'), ('a5', 'a5'), ('b5', 'b5'), ('b4', 'b4')], default='a4', max_length=300)),
                ('bending_type', models.CharField(choices=[('booklet', 'booklet'), ('book', 'book'), ('side clips', 'side clips'), ('corner clips', 'corner clips')], default='clips', max_length=300)),
                ('data_orderd', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_statis', models.CharField(choices=[('pending', 'pending'), ('working on', 'working on'), ('deliverd', 'deliverd'), ('complete', 'complete')], default='pending', max_length=300)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('location', models.CharField(default='', max_length=300)),
                ('notes', models.TextField(default='', max_length=1000)),
                ('user_acount', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
